### ISSUE TITLE
Mockups

### ISSUE THREAD

**Issue by OleFredrik1** [AndreasJJ/webtek#2]
Vi trenger "bilder" av hvordan de ulike delsidene skal se ut.

**Comment by AndreasJJ** [comment]
Forside mockup har blitt lagt til.
Timeline mockup har blitt lagt til.
Kontakt oss mockup har 2 forskjellige eksempler vi kan velge mellom. Velg den dere synes ser best ut.

**Comment by OleFredrik1** [comment]
P2 er ferdig og mockupsene er levert.
